### ISSUE TITLE
Hardcoded address

### ISSUE THREAD

**Issue by bearcanrun** [Superalgos/ALGOToken#13]
This is most likely a non-issue. `address(0)` is used AlgoFees.sol(L:29) as a marker for unregistered miners. In AlgoMiner.sol(L:114, L:115) is used in `stopAndRemoveOwnership()` and to reset `_miner` and `_referral`.

Warning states: _The contract contains unknown address. This address might be used for some malicious activity. Please check hardcoded address and it's usage._

Source: [SmartCheck Analysis](https://tool.smartdec.net/scan/e3c7fbd47ddb46478e9ec131a222a519)

**Comment by pmmax** [comment]
Yes, I haven't found another way to reset those unused variables.
I understand to goal of the SmartCheck Analysis, but here I'm using the address 0 just to express an uninitialized value, the SmartCheck Analysis is warning because it understands that this could be a hardcoded account or contract address.

**Comment by bearcanrun** [comment]
Thank you for confirming and explaining the non-issue!
